(function(){var d=void 0,g=true,i=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:da;return s.apply(i,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.ka=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(){}
function ha(a,b,c){switch(typeof b){case "string":ia(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var e=b.length;c.push("[");for(var f="",h=0;h<e;h++)c.push(f),ha(a,b[h],c),f=",";c.push("]");break}c.push("{");e="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(h=b[f],typeof h!="function"&&(c.push(e),ia(f,c),c.push(":"),ha(a,h,c),e=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ja={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ma=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ia(a,b){b.push('"',a.replace(ma,function(a){if(a in ja)return ja[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return ja[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},oa={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function pa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function qa(a,b){var c="",e=ra(encodeURIComponent(a));e.splice(b||5,e.length);t(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ra(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,h=271733878,p=3285377520,r=[],o,E,H,R,X,ga=Math.ceil((a.length/4+2)/16),ca=[ga],N=0,D;N<ga;N++){ca[N]=[];for(o=0;o<16;o++)ca[N][o]=a.charCodeAt(N*64+o*4)<<24|a.charCodeAt(N*64+o*4+1)<<16|a.charCodeAt(N*64+o*4+2)<<8|a.charCodeAt(N*64+o*4+3)}N=(a.length-1)*8;a=ga-1;ca[a][14]=Math.floor(N/Math.pow(2,32));ca[a][15]=N&4294967295;for(N=0;N<ga;N++){for(D=0;D<16;D++)r[D]=
ca[N][D];for(D=16;D<80;D++)r[D]=(r[D-3]^r[D-8]^r[D-14]^r[D-16])<<1|(r[D-3]^r[D-8]^r[D-14]^r[D-16])>>>31;a=c;o=e;E=f;H=h;R=p;for(D=0;D<80;D++)X=Math.floor(D/20),X=(a<<5|a>>>27)+(X==0?o&E^~o&H:X==1?o^E^H:X==2?o&E^o&H^E&H:o^E^H)+R+b[X]+r[D]&4294967295,R=H,H=E,E=o<<30|o>>>2,o=a,a=X;c=c+a&4294967295;e=e+o&4294967295;f=f+E&4294967295;h=h+H&4294967295;p=p+R&4294967295}return[c,e,f,h,p]}
function sa(a){var b=q.navigator,c=q.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;e=e.concat([b&&b.now?b.now():"",document.title,q.location.href,u(),pa()]);return e.concat(a||[]).join()}function v(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function ta(a){return a.replace(/^www\./,"")}var ua=/^((https?\:)?(\/\/))/i;function va(a){return a.replace(ua,"")}var wa=/^((https?\:)?(\/\/))?[^\/]*/;function xa(a){return a.replace(wa,"")}var ya=/\#.*/;function za(a){return a.replace(ya,"")}var Aa=/\?[^\#]*/;function Ba(a){return a.toLowerCase()}var Ca=/\/+((\?|\#).*)?$/;function Da(a){return a.replace(Ca,"$1")}function Ea(a){return a.replace(Aa,"")}
function Fa(a,b){if(a===b)return 0;var c=i;t([Ba,Da,va,xa,za,Ea],function(e,f){a=e(a);b=e(b);if(a===b)return c=f+1,j});return c}function x(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function Ga(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ha(a){return typeof a==="number"}function Ia(a){return typeof a==="string"}function Ja(a){return typeof a==="function"}
function Ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}function La(a){return encodeURIComponent(a)}function Ma(){return q.location.protocol==="https:"?"https:":"http:"}function t(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function Na(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}
function Oa(a){var b=q.pSUPERFLY_video,a=Na(b,a);if(a>-1)return b[a]}function Pa(a){return a===d?0:u()-a}function Qa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var h=0,p=a.length;h<=p;h++)c[0][h]=h;for(var r,o,E,e=1;e<=f;e++)for(h=1;h<=p;h++)r=e-1,o=h-1,E=c[r][o],b.charAt(r)==a.charAt(o)?c[e][h]=E:(o=c[e][o]+1,r=c[r][h]+1,E+=2,c[e][h]=Math.min(o,r,E));return c[b.length][a.length]}
function Ra(a){return a===d?0:u()-a}function y(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}var Sa,Ta=q.setInterval,Ua=q.clearInterval,Va=q.setTimeout,Wa=q.clearTimeout;function Xa(a,b){return Ta(a,b)}function Ya(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function Za(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function $a(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function ab(a,b,c){c=c||"";if(a===d)a=j;else{var e;if(!(e=c===""&&a.getAttribute(b)))if(e=a.getAttribute(b))e=a.getAttribute(b)===c;a=e?a:a===document.body?j:ab(a.parentNode,b,c)}return a}
function bb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=$a("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ha(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function cb(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function db(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function eb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var e=a.ownerDocument.documentElement,f=0,h=w(c)?c+1:-1;Ia(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==h;){if(c(a))return a;a=a.parentNode;f++}return i}
function fb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function gb(a){a=a||window.event;return!a?i:eb(a.target||a.srcElement,fb,10)}function hb(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c};function ib(){this.ma={};this.Va=1}function z(a,b,c,e){a.Va++;a.ma[b]=a.ma[b]||{};a.ma[b][a.Va]=[c,e];return a.Va}function jb(a,b){if(Ia(b))a.ma[b]=d,delete a.ma[b];else if(Ha(b)){var c=g;t(a.ma,function(a){t(a,function(f,h){if(parseInt(h,10)===b)return a[h]=d,delete a[h],c=j});return c})}}ib.prototype.xa=function(a,b){if(this.ma[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.ma[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
ib.prototype.addEventListener=function(a,b){var c=z(this,a,b);b._cbEventId=c};ib.prototype.removeEventListener=function(a,b){this.ma[a]&&this.ma[a][b._cbEventId]&&this.ma[a][b._cbEventId][0]===b&&jb(this,b._cbEventId)};var A=new ib;var B={};
B.H=function(){B.Pb?B.rb("pageload"):(B.Rc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],B.xb=i,B.Ia=i,B.Ob={},B.Nb={},B.zc={},B.Ab={},t(B.Rc,function(a){var b=a.event;x(a.target,b,function(a){B.rb.call(B,b,a)})}),z(A,"f",function(){B.rb("focus")}),B.rb("pageload"),x(document.body,"click",function(a){(a=gb(a))&&A.xa("c",a)},g),x(document.body,"contextmenu",function(a){(a=gb(a))&&
A.xa("r",a)}),B.Pb=g)};B.Yc=function(){var a,b=B.zc.keydown;if(b===d)return j;b=u()-b;return b<=(a||15E3)&&b>=0};B.Xa=function(a,b){var c=B.Ab[a];if(!c)return"";var b=b||u(),e,f=0;t(c,function(a){e=Math.floor((b-a)/1E3);e>=0&&e<16&&(f|=1<<e)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};B.Zd=function(){B.Ab={}};B.pc=100;
B.rb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}B.fe(a);if(B.xb===i)B.Mc(a);else if(!B.Ia||na[B.Ia]<na[a]||oa[B.Ia]<oa[a])B.Ia=a};B.fe=function(a){var b=u();B.zc[a]=b;var c=B.Ab[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();B.Ab[a]=c};
B.Mc=function(a){B.xb=Va(B.dd,B.pc);A.xa("a");B.Ob[a]!==i&&Wa(B.Ob[a]);B.Nb[a]!==i&&Wa(B.Nb[a]);B.Lc(a,B.Ob,na,"i");B.Lc(a,B.Nb,oa,"j")};B.Lc=function(a,b,c,e){b[a]=Va(function(){Wa(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||A.xa(e)},c[a]+B.pc)};B.dd=function(){Wa(B.xb);B.xb=i;if(B.Ia)B.Mc(B.Ia),B.Ia=i};var kb,lb,mb,nb,ob;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==d&&(nb=a,ob=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),mb=b+"visibilitychange")})();var pb=j;function qb(){pb=ob&&q.document[ob]==="prerender"?g:j}function rb(){lb=g;A.xa("f")}function sb(){lb=j;A.xa("b")}
function tb(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function ub(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;nb&&(b=q.document[nb]);return a&&!b}function vb(){ub()?rb():sb()}function wb(a){qb();if(pb){var b=j,c=function(){b||(qb(),pb||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(mb,c,j)},100)))};q.document.addEventListener(mb,c,j)}else a()};function xb(){this.k=q._sf_async_config||{};this.tc=v(this.Fc,this)}xb.prototype.H=function(){this.Hc=0};xb.prototype.Fc=k();xb.prototype.eb=function(a){if(!pb){var b=this.tc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};xb.prototype.wa=function(){this.tc=i};function yb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function zb(a,b){var c="",e=q.location.href.match(/[^?]+[?]([^#]+).*/);if(e){var e=yb(e[1]),f=b||a;e[f]&&(c=e[f])}return encodeURIComponent(c)}function Ab(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Bb(a){var b=[];t(Cb,function(c){var e=a[c];w(e)&&(Object.prototype.toString.call(e)==="[object Array]"?t(e,function(a){b.push(c+"="+a)}):e&&e.constructor===Object?t(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function Db(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=Ab(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,h=f.indexOf("?");h===-1&&(h=f.indexOf("#"));if(h===-1)h=f.length;h=f.lastIndexOf("/",h);a=h===-1?
"/"+a:f.substr(0,h)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Ab(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Eb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function C(a,b,c){a[b]=a[b]||c}function Fb(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function Gb(a){t(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=yb(b.src.split("?")[1]),C(a,"uid",b.uid),C(a,"domain",b.domain),j})}function Hb(a,b){return a[b]?encodeURIComponent(a[b]):""}function Ib(a){var b={};t(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var F={};F.ad=function(){try{F.create("_cb_test","1",1);var a=F.F("_cb_test");F.remove("_cb_test");return a==="1"}catch(b){return j}};F.F=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
F.create=function(a,b,c){var e=q._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(u()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+"; path=/";return document.cookie=a};F.remove=function(a){return F.F(a)?F.create(a,"",-86400):""};var G={};G.Y=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return i;if(G.Y.Gb!==d)return G.Y.Gb;var a=u()+"",c,e;try{if((e=q.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return G.Y.Gb=e}catch(f){}return G.Y.Gb=i};G.F=function(a){var b=G.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var e=G.Y();if(e){var f=new Date;f.setTime(u()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(h){}}};G.remove=function(a){var b=G.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Jb(a){this.tb=a||"";this.ed=G.Y()!==i||F.ad();this.hc=j;Kb(this)}n=Jb.prototype;n.isSupported=l("ed");
function Kb(a){if(!F.F("_cb_ls")){var b=G.Y()!==i,c=F.F("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,g)});var e=F.F("_chartbeat3");e&&(a.create("_v__chartbeat3",e,34128E3,g),F.remove("_chartbeat3"));b&&((b=F.F("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,g),(b=F.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));F.create("_cb_ls","1",34128E3)}}function Lb(a){var b=a.hc;a.hc=j;return b}
n.create=function(a,b,c,e){a=e?a:this.tb+a;(G.Y()?G:F).create(a,b,c);G.Y()&&F.create(a,b,c)};n.update=function(a,b,c,e,f,h,p){a=e?a:this.tb+a;f=Ia(f)?f:"::";e=(e=this.F(a,g))?e.split(f):[];if(p&&e.length){var r=p(b),o=Na(e,function(a){return p(a)===r});o!==-1&&e.splice(o,1)}e.push(b);for(Ha(h)&&e.length>h&&e.splice(0,e.length-h);e.length>1&&e.join(f).length>4E3;)e.shift();this.create(a,e.join(f),c,g)};
n.F=function(a,b){var a=b?a:this.tb+a,c=(G.Y()?G:F).F(a);if(!c&&G.Y()&&(c=F.F(a))&&F.F("_cb_ls")){this.hc=g;var e;switch(a){case "_SUPERFLY_lockout":e=600;break;case "_chartbeat4":e=60;break;case "_cb_cp":e=60;break;case "_chartbeat3":e=34128E3;break;default:e=34128E3}G.create(a,c,e)}return c};n.remove=function(a,b){a=b?a:this.tb+a;(G.Y()?G:F).remove(a);G.Y()&&F.remove(a)};function Mb(a){var b=i;if(a&&(b=Nb()))return b;var c=q.location,b=Ob(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function Nb(){var a=i;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Db(b.href),a=Ob(b.pathname)+b.search+b.hash,j});return a}
for(var Pb={},Qb=0;Qb<81;Qb++)Pb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Qb)]=g;function Rb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Pb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Ob(a){if(!Ia(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Rb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function I(a,b){var c=J();return w(b)&&!w(c[a])?b:c[a]}function J(){w(q._cb_shared)||(q._cb_shared={});return q._cb_shared};var K={Uc:{IDLE:0,Tc:1,Sc:2,Cb:3},Vc:{IDLE:0,Tc:1,Sc:2,Cb:3},pa:0,qa:0};K.H=function(){if(!K.Pb)z(A,"a",K.nd,K),z(A,"i",K.rd,K),z(A,"f",K.pd,K),z(A,"b",K.od,K),z(A,"j",K.qd,K),K.Pb=g};K.J=function(){return K.pa};K.ld=function(){return K.qa};K.nd=function(){K.pa===1?K.Ea(3):K.pa===0&&K.Ea(2);K.qa===1?K.Da(3):K.qa===0&&K.Da(2)};K.rd=function(){K.pa===3?K.Ea(1):K.pa===2&&K.Ea(0)};K.qd=function(){K.qa===3?K.Da(1):K.qa===2&&K.Da(0)};K.pd=function(){(K.pa===0||K.pa===2)&&K.Ea(3);(K.qa===0||K.qa===2)&&K.Da(3)};
K.od=function(){K.pa===3?K.Ea(2):K.pa===1&&K.Ea(0);K.qa===3?K.Da(2):K.qa===1&&K.Da(0)};K.Ea=function(a){K.pa=a;A.xa("s",a)};K.Da=function(a){K.qa=a;A.xa("x",a)};function Sb(a,b){this.Mb=a||d;this.Vb=b||d;this.Pa=this.ua=0;this.yc=v(this.wd,this);this.gc=this.ra=i}n=Sb.prototype;n.H=function(){this.Pa=this.ua=0;this.ra=i;this.gc=z(A,"s",this.Za,this);this.Za(K.J())};n.Za=function(a){Ua(this.ra);this.ra=i;if(a===K.Uc.Cb)this.ra=Ta(this.yc,1E3)};n.wd=function(){if(this.Mb===d||this.Mb())this.ua++,this.Pa++,this.Vb&&this.Vb()};n.terminate=function(){Ua(this.ra);this.ra=i;jb(A,this.gc)};n.wa=function(){this.terminate();this.Vb=this.Mb=d};function Tb(a,b){Sb.call(this,a,b)}ea(Tb,Sb);Tb.prototype.H=function(){this.Pa=this.ua=0;this.ra=i;this.gc=z(A,"x",this.Za,this);this.Za(K.ld())};Tb.prototype.Za=function(a){Ua(this.ra);this.ra=i;if(a===K.Vc.Cb)this.ra=Ta(this.yc,1E3)};function L(){xb.call(this);this.Ma=[];this.q=new Jb(this.Oc);this.q.remove("_SUPERFLY_nosample");this.la=new Sb;this.Ja=new Tb;this.Xb=v(this.bb,this);x(q,"unload",this.Xb);wb(v(this.H,this))}ea(L,xb);n=L.prototype;n.dc=g;
n.H=function(){L.ka.H.call(this);this.nb=this.Qa=0;this.Fa=u();this.Ca=qa(Ub(this));this.bc=g;this.pb=72E5;if(this.dc){var a=+this.k.sessionLength;if(!isNaN(a))this.pb=a*6E4}a=I("d");if(!a){var a=[],b=this.q.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=u(),c=this.q.F("_cb",g);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var e=b-+(a[1]||0),f=b-+(a[2]||0);J().n=c&&e>18E5&&f<2592E6?0:1;e=a[4];if(!(f=f>18E5))if(Vb(this))f=j;else{var f=Wb(this),f=decodeURIComponent(f),f=Xb(f)||f,
h;h=Yb(this);h=decodeURIComponent(h);h=Xb(h)||h;f=f!==h}if(!e||f)e=qa(Ub(this)),a[4]=e,this.q.remove("_cb_svref",g);f="1";h=a&&+a[2];e=a&&a[3];if(a&&h&&e)if(f=Math.abs((Ka(b)-Ka(h))/864E5)){f=Math.min(f,16)-1;for(h="";f--;)h+=0;f=(e+h+"1").slice(-16)}else f=e;e=f;c||(c=this.k.utoken||qa(Ub(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.gb;this.q.create("_cb",c,34128E3,g);this.q.create("_chartbeat2",a.join("."),34128E3,g);a[0]=c;J().d=a}this.oe=a.join(".");var p;c=+a[1];e=+a[2];if((b=a[3])&&c&&
e)p=(Math.min((Math.abs((Ka(e)-Ka(c))/864E5)||0)+1,16,b.length)-1).toString(16),p+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.xc=p;this.Sb=I("n",1);this.gb=a[0];this.be=a[4];this.ae=Yb(this);this.q.create("_cb_svref",Yb(this)||"null",1800,g);this.la.H();this.Ja.H();K.H();B.H();kb||(lb=ub(),mb&&q.document.addEventListener&&q.document.addEventListener(mb,vb,j),tb("focus","onfocusin",rb),tb("blur","onfocusout",sb),lb&&rb(),kb=g);this.ab=0;this.Xc=z(A,"a",this.zd,this)};
function Zb(a){if(!a.q.F("_SUPERFLY_lockout")&&!pb)a.yd?a.vb():(a.yd=g,!q._sf_async_config&&!q._cbq?(a.sb=v(a.vb,a),x(q,"load",a.sb)):a.vb())}n.vb=function(){this.cb=$b();B.H();this.lb=Xa(v(this.na,this),15E3);this.na()};
n.na=function(){var a=this.la.Pa,a=this.k.reading&&+this.k.reading||a>0;if(this.nb<this.Qa&&!a)this.nb++;else{var b;if(Sa===d)b=q.navigator.userAgent,Sa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Sa;b&&!a?this.nb++:(a?this.Qa=0:this.Fb(),this.nb=0,this.Ma.push(0),this.Ma.length>18&&this.Ma.shift(),this.dc&&u()-this.Fa>=this.pb?this.terminate():this.Ua())}};
n.Fc=function(){this.Ma.push(1);var a=0;t(this.Ma,function(b){a+=b});a<3?(this.bc=g,this.Fb()):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};n.bb=k();n.zd=function(){var a=ac(this);this.ab=Math.max(this.ab,a)};function ac(a){return Math.floor(bb(!!a.k.scrollElement))}n.Fb=function(){var a=this.Qa;this.Qa=a=a?Math.min(a*2,16):1};n.kb=function(){this.bb();this.terminate()};n.Nc=function(){this.H();Zb(this)};
function Vb(a){if(a.k.virtualReferrer)return g;if(bc(a))return j;a=document.referrer.indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function bc(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function Wb(a){a=a.k.virtualReferrer||bc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Db(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Ob(b.pathname),a=Eb(b)}return encodeURIComponent(a)}function cc(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Ub(a){a=[Wb(a),db("Width"),db("Height")];return sa(a)}
function dc(a){var b=[],c=a.q.F("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}function Yb(a){a=a.q.F("_cb_svref",g)||Wb(a)||"null";a==="null"&&(a="");return a}function Xb(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function $b(){var a=q.performance&&q.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ha(b)&&b?Ha(a)&&a>b?a-b:u()-b:-1}
n.terminate=function(){this.la.terminate();this.Ja.terminate();jb(A,this.Xc);this.sb!==d&&Ga(q,"load",this.sb);Ua(this.lb);J().d=d;J().n=d};n.wa=function(){this.terminate();Ga(q,"unload",this.Xb);this.Xb=this.sb=this.q=this.Ma=this.k=i;this.la.wa();this.la=i;this.Ja.wa();this.Ja=i;L.ka.wa.call(this)};function ec(a){for(var b=I("m")||[];b.length;)a(b.shift());a={push:a};J().m=a};function fc(a){var b=a.offsetLeft,c=a.offsetTop,e=gc(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=gc(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(hc(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function hc(a,b){var c={},e,f;q.getComputedStyle?e=q.getComputedStyle(a,i):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var ic=/matrix(3d)?\((.*)\)/;function gc(a){var b={x:0,y:0},a=hc(a,["transform"]).transform;if(!Ia(a))return b;var c=a.match(ic);if(!c)return b;var a=c[2].split(", "),e;w(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function jc(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=Db(a);a.pathname=Ob(a.pathname);return a}
function kc(a){var b=F.F("_chartbeat6");if(!b)return i;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,h=jc(),p=Eb(h);t(b,function(a,b){var h=a.split(","),o=Qa(p,decodeURIComponent(h[0]));if(o===0)return c=h,e=b,j;if(f===d||o<f)f=o,c=h,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+lc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),h=decodeURIComponent(c[1]),r=c[2];c.splice(0,3);for(var o=c.length/2,E=0;E<o;E++)a.push({le:b,origin:h,Ra:r,gd:c[E*2],ge:c[E*2+1]});
return a}function lc(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.Cc&&(c=new Date,c.setTime(c.getTime()+a.Cc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function mc(a){var b=a.topStorageDomain,a=a.domain,c=q.location.hostname;return b?b:nc(c,a)?a:c.replace(/^www\./,"")}function nc(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g}
function oc(a,b,c,e){this.jd=a;this.hd=b;this.he=c;this.Ra=e};function pc(a,b){for(var c=b||document.documentElement,e=[],f=i,h=a,p,r,o,E,H,R;h&&h!==c;){p=h.nodeName.toLowerCase();f=h;r=f.nodeName;if((h=h.parentNode)&&h!==document.documentElement){o=h.children;E=0;for(H=0,R=o.length;H<R;H++){if(f===o[H]){p+="["+(1+H-E)+"]";break}o[H].nodeName!==r&&E++}}e.unshift(p)}return e.join("/")};function qc(){this.Oc="_t_";L.call(this)}ea(qc,L);n=qc.prototype;
n.H=function(){qc.ka.H.call(this);Gb(this.k);var a=q.location;C(this.k,"mabServer","mabping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);C(this.k,"path",Mb(!!this.k.useCanonical));this.ja=ta(a.hostname);this.k.domain=ta(this.k.domain);this.ee=mc(this.k);this.Wa=this.ob=j;this.uc=[];var b=this,a=kc({domain:"."+this.ee,Cc:6E4,path:"/"});if(a!==i)this.ob=g,t(a,function(a){b.uc.push(new oc(a.origin,a.gd,a.ge,a.Ra))});this.Dc=0;this.wb=i;ec(v(this.vd,this))};
n.Ua=function(){var a=this.la.ua,b=rc(this),c,e=this;this.ob&&t(this.uc,function(f){c=b+"&x="+f.hd+"&v="+f.he+"&ml="+f.Ra+"&xo="+f.jd+"&e="+a;e.eb(c)});!this.Wa&&this.wb&&sc(this,this.wb);this.Wa=g};n.vb=function(){this.cb=$b();B.H();if(this.ob)this.lb=Xa(v(this.na,this),500);this.na()};n.na=function(){var a,b;this.Wa?(a=this.la.ua,b=this.Dc*15,a-b>=15&&(this.Ua(),this.Dc+=1),a>=45&&this.terminate()):this.Ua()};
function rc(a){var b=a.k;return Ma()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ja)+"&u="+a.gb+"&c="+Math.round((u()-a.Fa)/600)/100}n.bb=k();n.ce=function(a){var b=a.d,c=i;b!==i&&(c={ec:b.s,Ra:b.g,Bc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Wa?sc(this,a):this.wb=a};
function sc(a,b){var c=rc(a),e=b.status,f=b.data;if(e=="s"&&f!==i){var h=v(a.eb,a);f.ec&&f.ec.constructor===Object&&t(f.ec,function(a,b){h(c+"&x="+b+"&v="+a+"&ml="+f.Ra+"&e=-1")});Object.prototype.toString.call(f.Bc)==="[object Array]"&&t(f.Bc,function(a){h(c+"&me=3&ml="+f.Ra+"&x="+a)})}else e=="e"&&a.eb(c+"&me="+b.code)}n.vd=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.ce.apply(this,a):f==="v"&&this.$d.apply(this,a)}};
n.kb=function(){J().m=[];w(this.kc)&&this.kc();qc.ka.kb.call(this)};n.$d=function(a){this.kc=a};n.terminate=function(){this.kc=this.me=d;this.wb=i;this.Wa=this.ob=d;qc.ka.terminate.call(this)};if(!q.pSUPERFLY_mab){var tc=new qc,uc={};uc.evps=v(tc.kb,tc);uc.svps=v(tc.Nc,tc);q.pSUPERFLY_mab=uc;Zb(tc)};var vc,wc,xc;
function yc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);zc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(d)?d:{},b.src=a,a=hb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(d)?d.appendChild(a):b&&b.appendChild(a)}}
function zc(){Wa(wc);wc=d;Ga(q,"message",yc);xc&&xc.parentNode&&xc.parentNode.removeChild(xc);xc=d};function Ac(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!vc){vc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);x(q,"message",yc);wc=Va(zc,1E4);var b=w(d)?d:{};b.src=a;a=hb("iframe",b);a.style.display="none";w(d)?d.appendChild(a):document.body&&document.body.appendChild(a);xc=a}}
function Bc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=G.Y(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Ac(),Ga(q,"message",Bc))}};function Cc(){"postMessage"in window&&x(q,"message",v(this.sd,this));L.call(this);Fb("_cbq",v(this.Kc,this))}ea(Cc,L);
Cc.prototype.H=function(){Cc.ka.H.call(this);var a=this.gb;J().u=a;a=this.Ca;J().t=a;this.Eb=i;Gb(this.k);a=q.location;C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);this.k.path=this.k.path?Ob(this.k.path):Mb(!!this.k.useCanonical);this.ja=ta(a.hostname);this.k.domain=ta(this.k.domain);this.Zc=z(A,"c",this.Dd,this);this.$c=z(A,"r",this.Ed,this);this.Oa=i};Cc.prototype.Wc=function(a){this.Eb=a};
Cc.prototype.bb=function(){this.q.update("_chartbeat4",["t="+this.Ca,"E="+this.la.ua,"EE="+this.Ja.ua,"x="+ac(this),"c="+Math.round((u()-this.Fa)/600)/100,"y="+db("Height"),"w="+cb()].join("&"),60,d,d,1)};var Cb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv,sr".split(",");n=Cc.prototype;
n.Ua=function(a){this.Hc++;var b={};b.g=this.k.uid;b.g0=Hb(this.k,"sections");b.g1=Hb(this.k,"authors");b.g2=Hb(this.k,"zone");b.g3=Hb(this.k,"sponsorName");b.g4=Hb(this.k,"type");!this.k.noCookies&&this.q.isSupported()?b.n=this.Sb:b.nc=1;b.c=Math.round((u()-this.Fa)/600)/100;b.E=this.la.ua;b.EE=this.Ja.ua;var c=ac(this);this.ab=Math.max(this.ab,c);b.x=c;b.m=this.ab;b.y=db("Height");b.o=db("Width");b.w=cb();b.b=this.cb>0?this.cb:"";if(this.xc)b.f=this.xc;b[""]=Ib(this.k);b.t=this.Ca;b.V=94;b.tz=(new Date).getTimezoneOffset();
b.sn=this.Hc;b.sv=this.be;b.sr=this.ae;c=this.la.Pa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.gb;b.d=encodeURIComponent(this.ja);b.j=Math.round((this.Qa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var e=b.c*6E4+this.Fa;b.eD=B.Xa("mousedown",e);b.eM=B.Xa("mousemove",e);b.eK=B.Xa("keydown",e);b.eR=B.Xa("resize",e);b.eS=B.Xa("scroll",e);B.Zd();B.Yc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Vb(this);if(this.bc){this.bc=j;if(c)this.Oa=Dc(this);
b.i=cc(this);e=this.k.hudTrackable;e!==d&&(b.L=e?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Oa){if(b.v=encodeURIComponent(this.Oa.path),b.K=Ec(this.Oa),this.Oa.Tb>1)b.l1=this.Oa.Tb}else b.v=Wb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Wb(this);c=Ya(b.v);J().v=c;c=Ya(b.r);J().r=c;b.A=this.Eb?this.Eb:"";b._c=zb("utm_campaign",this.k.campaignTag);b._m=zb("utm_medium",this.k.mediumTag);b._x=zb("utm_source",this.k.sourceTag);b._y=zb("utm_content",this.k.contentTag);
b._z=zb("utm_term",this.k.termTag);this.k.idSync?(c=[],ha(new fa,this.k.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=dc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Ec(a):"";b.l=Lb(this.q)?1:"";this.la.Pa=0;this.eb(Ma()+"//"+this.k.pingServer+"/ping?"+Bb(b))};
n.sd=function(a){var b=this.k,c=b.playerdomain||this.ja;if(va(a.origin)===va(c))if(c=a.data,Ia(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Kc(a));else if(c=="cbdata?"){var c="&u="+I("u"),e="&t="+I("t"),f="&v="+I("v"),h="&r="+I("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+cc(this)+"&referrer="+Wb(this)+"&internal="+(Vb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ja)+
c+e+f+h+"&utoken="+this.gb;a.source.postMessage(b,"*")}};n.Kc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Qa=0};function Fc(a){a=a.replace(/-{2,}/g,"-");a=Db(a);a.pathname=Ob(a.pathname);return a}n.Dd=function(a){Gc(this,a,"c")};n.Ed=function(a){Gc(this,a,"r")};
function Gc(a,b,c){if(a.dc&&u()-a.Fa>=a.pb)a.terminate();else{var e=b.href||"",e=Fc(e);if(e.protocol.indexOf("http")===0){var f=e.hostname!==q.location.hostname,e=Eb(e),h=eb(b,function(a){return a.id}),p=pc(b,h),r="";a.k.moduleAttribute&&(r=(r=ab(b,a.k.moduleAttribute))?r.getAttribute(a.k.moduleAttribute):"",r=r.replace(/::/g,"-").substr(0,40));h?(p&&(p="/"+p),p="*[@id='"+h.id+"']"+p,h=pc(b)):h=p;p=qa(p);h=qa(h);b=fc(b);c={left:b.x,top:b.y,path:a.k.path,href:e,oc:p,Db:h,mc:"",fc:c,Tb:0,md:a.k.domain,
Rb:r};a.Ua(c);f||a.q.update("_chartbeat5",Hc(c),60,j,d,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function Ec(a){return[a.left,a.top,a.oc,encodeURIComponent(a.mc),a.fc,encodeURIComponent(a.href),a.Db,a.Rb].join("::")}function Hc(a){var b=encodeURIComponent(a.mc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.oc,b,a.fc,a.Db,encodeURIComponent(a.md),a.Rb].join(",")}
function Dc(a){var b=a.q.F("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,e,f=i,h,p=Fc(q.location.href),r=Eb(p);t(c,function(a,b){var c=a.split(","),p=Fa(r,decodeURIComponent(c[3]));if(p===0)return e=c,f=b,j;else if(p===i)return g;if(h===d||p<h)h=p,e=c,f=b});if(f===i)return i;c.splice(f,1);a.q.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),oc:e[4]||
"",mc:"",Db:e.length>7?e[7]:"",fc:e.length>6?e[6]:"c",Tb:b,Rb:e[9]?e[9]:""}}n.terminate=function(){jb(A,this.Zc);jb(A,this.$c);Cc.ka.terminate.call(this)};var M="ct",O="s1";function P(a){this.a=a;this.D=this.G=j;this.B=u();this.ha()}n=P.prototype;n.ha=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.on("play",v(this.fa,this));this.a.on("dispose",v(this.Gd,this));this.a.ready(v(this.oa,this))};n.oa=function(){this.G=g};n.fa=function(){this.D=g};n.Gd=function(){var a=q._cbv;a&&a.push&&a.push(["removePlayer",this.a])};n.O=function(){return this.G&&this.M()!==""};
n.Kb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};n.Lb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};n.M=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
n.N=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.duration();return y(a)};n.J=function(){return!this.D?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};n.X=function(){var a=this.a.currentTime();return y(a)};n.T=m(-1);
n.ba=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};n.Z=k();n.S=k();n.da=function(){return Ra(this.B)};n.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
n.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};n.aa=m("BCN");P.prototype.getStrategyName=P.prototype.aa;P.prototype.isReady=P.prototype.O;P.prototype.getHost=P.prototype.Kb;P.prototype.getUid=P.prototype.Lb;P.prototype.getTitle=P.prototype.M;P.prototype.getVideoPath=P.prototype.N;
P.prototype.getContentType=P.prototype.U;P.prototype.getAdPosition=P.prototype.P;P.prototype.getTotalDuration=P.prototype.ca;P.prototype.getState=P.prototype.J;P.prototype.getCurrentPlayTime=P.prototype.X;P.prototype.getBitrate=P.prototype.T;P.prototype.getThumbnailPath=P.prototype.ba;P.prototype.getPlayerType=P.prototype.Z;P.prototype.getAutoplayType=P.prototype.S;P.prototype.getViewStartTime=P.prototype.da;P.prototype.getSections=P.prototype.$;P.prototype.getAuthors=P.prototype.Q;
P.verify=function(a){return a.controlBar!==d};function Q(a){this.Va=this.ja=d;this.G=j;this.Jc=this.rc=-1;this.va=i;this.a=a;this.D=j;this.Yb=g;this.B=u();this.Zb="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.Zb=e;break}}if(this.Zb){a=yb(this.Zb);if(this.ja=a.domain)this.ja=this.ja.replace(/^video@/,"");this.Va=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Gc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Gc,this))}n=Q.prototype;
n.Gc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.rc=Math.round(a)});b.getCurrentVideo(function(a){c.va=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.Od,this));b.addEventListener(a.STOP,s(this.Qd,this));b.addEventListener(a.COMPLETE,s(this.Fd,this));b.addEventListener(a.BEGIN,s(this.fa,this));this.G=g};n.Od=function(a){this.Jc=a.position;this.za=this.Yb=j};n.Qd=function(){this.Yb=g};
n.Fd=function(){this.za=g};n.fa=function(){this.za=j;if(!this.D)this.D=g};n.O=l("G");n.M=function(){var a="";this.va&&(a=this.va.displayName);return a};n.N=function(){var a="";this.va&&(a="video@"+this.ja+"/"+this.va.id);return a};n.U=function(){return M};n.P=m("");n.ca=l("rc");n.J=function(){return!this.D?O:this.za?"s4":this.Yb?"s3":"s2"};n.X=function(){return y(this.Jc)};n.T=m(-1);n.ba=function(){var a="";this.va&&(a=this.va.thumbnailURL);return a};n.Z=k();
n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.Q=k();n.$=function(){var a;this.va&&(a=this.va.tags);return a};n.S=m("unkn");n.aa=m("BC");n.Kb=l("ja");n.Lb=l("Va");Q.prototype.isReady=Q.prototype.O;Q.prototype.getTitle=Q.prototype.M;Q.prototype.getVideoPath=Q.prototype.N;Q.prototype.getContentType=Q.prototype.U;Q.prototype.getAdPosition=Q.prototype.P;Q.prototype.getTotalDuration=Q.prototype.ca;Q.prototype.getState=Q.prototype.J;Q.prototype.getCurrentPlayTime=Q.prototype.X;
Q.prototype.getBitrate=Q.prototype.T;Q.prototype.getThumbnailPath=Q.prototype.ba;Q.prototype.getPlayerType=Q.prototype.Z;Q.prototype.getViewStartTime=Q.prototype.da;Q.prototype.getAuthors=Q.prototype.Q;Q.prototype.getSections=Q.prototype.$;Q.prototype.getAutoplayType=Q.prototype.S;Q.verify=function(a){return a===window.brightcove};Q.prototype.getStrategyName=Q.prototype.aa;Q.prototype.getHost=Q.prototype.Kb;Q.prototype.getUid=Q.prototype.Lb;function S(){this.a=window.flowplayer();this.D=this.G=j;this.B=u();this.ya=this.Ba=d;this.yb=this.fb="";this.Qb=d;this.ha()}var Ic=/url\(['"]?([^'"\)]*)['"]?\)/;n=S.prototype;
n.vc=function(){if(this.a.conf&&(this.yb=this.a.conf.title?this.a.conf.title:"",this.fb=this.a.conf.poster?this.a.conf.poster:"",this.yb&&this.fb))return g;var a=this.N(),b=$a("name","param"),c=d;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=$a("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=ab(c,"data-swf");if(b===j)return j;var e=b.style.background;if(e){if(e=
e.match(Ic))this.fb=e[1]}else this.fb=b.attributes.poster&&b.attributes.poster.value;this.yb=b.title;if(this.Qb!==d)clearInterval(this.Qb),this.G=g;return g};n.ha=function(){this.a.qe?this.oa():this.a.bind("ready",s(this.oa,this));this.a.bind("resume",s(this.fa,this));this.a.pe&&this.fa()};n.oa=function(){this.vc()===j?this.Qb=setInterval(s(this.vc,this),1E3):this.G=g};n.fa=function(){if(!this.D)this.D=g};n.O=l("G");n.M=l("yb");n.N=function(){return this.a.video.url||this.a.video.src};n.U=function(){return M};
n.P=m("");n.ca=function(){return this.a.video.duration&&this.a.video.duration*1E3};n.J=function(){return!this.D?O:this.a.ne?"s4":this.a.paused?"s3":"s2"};n.X=function(){return y(this.a.video.time)};n.T=m(-1);n.ba=l("fb");n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("FP");S.prototype.getStrategyName=S.prototype.aa;S.prototype.isReady=S.prototype.O;S.prototype.getTitle=S.prototype.M;S.prototype.getVideoPath=S.prototype.N;
S.prototype.getContentType=S.prototype.U;S.prototype.getAdPosition=S.prototype.P;S.prototype.getTotalDuration=S.prototype.ca;S.prototype.getState=S.prototype.J;S.prototype.getCurrentPlayTime=S.prototype.X;S.prototype.getBitrate=S.prototype.T;S.prototype.getThumbnailPath=S.prototype.ba;S.prototype.getPlayerType=S.prototype.Z;S.prototype.getAutoplayType=S.prototype.S;S.prototype.getViewStartTime=S.prototype.da;S.prototype.getSections=S.prototype.$;S.prototype.getAuthors=S.prototype.Q;S.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.Bb=this.D=this.G=j;this.B=u();this.ya=this.Ba=d;this.ha()}n=T.prototype;n.ha=function(){this.a.readyState>0&&this.oa();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.addEventListener("canplay",v(this.oa,this));var a=v(this.fa,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.Wd,this))};n.oa=function(){this.G=g};n.fa=function(){this.D=g;this.Bb=j};
n.Wd=function(){this.Bb=g};n.O=l("G");n.M=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};n.N=function(){return this.a.currentSrc||""};n.U=function(){return M};n.P=m("");n.ca=function(){return y(this.a.duration)};n.J=function(){return!this.D?O:this.a.ended||this.Bb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Bb?"s3":"s2"};n.X=function(){return y(this.a.currentTime)};n.T=m(-1);n.ba=function(){return this.a.poster||""};n.Z=k();
n.S=function(){return this.a.autoplay?"auto":"man"};n.da=function(){return Ra(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("H5");T.prototype.getStrategyName=T.prototype.aa;T.prototype.isReady=T.prototype.O;T.prototype.getTitle=T.prototype.M;T.prototype.getVideoPath=T.prototype.N;T.prototype.getContentType=T.prototype.U;T.prototype.getAdPosition=T.prototype.P;T.prototype.getTotalDuration=T.prototype.ca;T.prototype.getState=T.prototype.J;T.prototype.getCurrentPlayTime=T.prototype.X;
T.prototype.getBitrate=T.prototype.T;T.prototype.getThumbnailPath=T.prototype.ba;T.prototype.getPlayerType=T.prototype.Z;T.prototype.getAutoplayType=T.prototype.S;T.prototype.getViewStartTime=T.prototype.da;T.prototype.getSections=T.prototype.$;T.prototype.getAuthors=T.prototype.Q;T.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function U(a){this.a=a;this.D=this.za=this.G=j;this.B=u();this.$a=j;this.ha()}n=U.prototype;n.ha=function(){function a(a,f){f=s(f,c);if(aa(b.on)=="function")b.on(a,f);else{var h="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(aa(b[h])=="function")b[h](f)}}var b=this.a,c=this;a("ready",this.oa);a("time",this.Sd);a("complete",this.Td);a("adStarted",this.Sa);a("adPlay",this.Sa);a("adImpression",this.Sa);a("adTime",this.Sa);a("adComplete",this.Ub);a("adSkipped",this.Ub);a("adError",this.Ub)};
n.oa=function(){this.G=g};n.Sd=function(){this.za=j;this.D=g;this.$a=j};n.Td=function(){this.za=g};n.Sa=function(){this.$a=this.D=g};n.Ub=function(){this.$a=j};n.O=function(){this.a.getState();return this.G||this.a.getState()!==d};n.M=function(){var a=Jc(this);return!a?"":a.title};function Jc(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}
n.N=function(){var a=Jc(this);return!a?"":a.mediaid||a.file};n.U=function(){return this.$a?"ad":M};n.P=m("");n.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};n.J=function(){if(!this.D)return O;if(this.$a)return"s2";if(this.za)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};n.X=function(){var a=this.a.getPosition();return y(a)};n.T=m(-1);n.ba=function(){var a=Jc(this);return!a?"":a.image};n.Z=k();n.da=function(){return isNaN(this.B)?0:Pa(this.B)};
n.Q=k();n.$=k();n.S=m("unkn");n.aa=m("JW");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.M;U.prototype.getVideoPath=U.prototype.N;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.J;U.prototype.getCurrentPlayTime=U.prototype.X;U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;
U.prototype.getPlayerType=U.prototype.Z;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getAuthors=U.prototype.Q;U.prototype.getSections=U.prototype.$;U.prototype.getAutoplayType=U.prototype.S;U.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function V(a){this.a=a;this.Qc="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.ha()}n=V.prototype;n.ha=function(){this.a.kBind("playerStateChange.cb",s(this.Vd,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.Nd,this));this.a.kBind("playerPlayEnd.cb",s(this.Ud,this));this.a.kBind("adStart.cb",s(this.Sa,this));this.a.kBind("adEnd.cb",s(this.Ad,this));this.a.kBind("switchingChangeComplete.cb",s(this.Rd,this))};
n.Vd=function(a){switch(a){case "playing":this.ia="s2";break;case "buffering":this.ia="s3";break;case "paused":this.ia="s3"}};n.Nd=function(){this.ia="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};n.Ud=function(){this.ia="s4"};n.Sa=function(a){this.Aa="ad";switch(a){case "pre":this.sa="a1";break;case "post":this.sa="a3";break;case "mid":this.sa="a2";break;case "main":this.sa="a5"}};n.Ad=function(){this.Aa=M};n.Rd=function(a,b){this.bd=b};
n.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};n.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")};n.N=function(){if(!this.O())return this.Qc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Qc=a)||""};n.U=l("Aa");n.P=l("sa");n.ca=function(){var a=this.a.evaluate("{duration}");return y(a)};n.J=l("ia");n.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return y(a)};n.T=l("bd");
n.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};n.Z=k();n.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};n.da=function(){return isNaN(this.B)?0:Ra(this.B)};n.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
n.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};n.aa=m("KT");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.M;V.prototype.getVideoPath=V.prototype.N;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.J;V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;
V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getAutoplayType=V.prototype.S;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getSections=V.prototype.$;V.prototype.getAuthors=V.prototype.Q;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.qc=d;this.a=a;this.Ac=d;this.G=j;this.Ka=d;this.D=j;this.ya=this.Ba=this.B=d;this.qc=q.OO;this.Ac=this.a.mb;this.B=u();this.ha()}n=W.prototype;
n.ha=function(){var a=this.Ac,b=this.qc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.oa,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Cd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.fa,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Bd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.Md,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Hd,this))};n.oa=function(){this.G=g};
n.Cd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ka=a===0?"a1":Kc(a,b)?"a3":"a2"};n.fa=function(){this.D=g};n.Bd=function(){this.Ka=d};n.Md=k();n.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.G=g;return this.G};n.M=function(){var a=this.a.getItem();return a?a.title:""};
n.N=function(){var a=this.a.getEmbedCode&&this.a.getEmbedCode();if(a)return a;a=this.a.getItem()||{};return a.embed_code||a.embedCode||this.a.embedCode||""};n.U=function(){return this.Ka===d?M:"ad"};n.P=function(){return this.Ka?this.Ka:""};n.ca=function(){var a=this.a.getItem(),a=a&&a.duration||this.a.getDuration()*1E3;return a===-1||!isFinite(a)?-1:a};
n.J=function(){if(!this.D)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Kc(a,b)?"s4":"s2"};function Kc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}n.Hd=function(){this.Ka=d};n.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};
n.T=function(){var a=this.a.getCurrentBitrate&&this.a.getCurrentBitrate();return a?a.bitrate:0};n.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Ra(this.B||0)};n.$=l("Ba");n.Q=l("ya");n.aa=m("OO");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.M;W.prototype.getVideoPath=W.prototype.N;W.prototype.getContentType=W.prototype.U;
W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.J;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;
W.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("isAdPlaying")};function Y(a){this.a=a;this.ga=i;this.Ya="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}n=Y.prototype;n.xd=function(a){this.ha(a.controller)};
n.ha=function(a){a.addEventListener("OnLoadRelease",v(this.Ec,this));a.addEventListener("OnLoadReleaseUrl",v(this.Ec,this));a.addEventListener("OnReleaseStart",v(this.Pd,this));a.addEventListener("OnMediaPlay",v(this.Jd,this));a.addEventListener("OnMediaStart",v(this.Ld,this));a.addEventListener("OnMediaPause",v(this.Wb,this));a.addEventListener("OnMediaComplete",v(this.Id,this));a.addEventListener("OnMediaError",v(this.Wb,this));a.addEventListener("OnMediaBuffer",v(this.Wb,this));a.addEventListener("OnMediaPlaying",
v(this.Kd,this))};n.Ec=function(a){if(a.data&&a.data.title)this.ga=a.data;if(a.data&&a.data.guid)this.Ya=a.data.guid};n.Pd=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.Ya=a,j},this));if(this.Ya&&a.data.release&&a.data.release.title)this.ga=a.data.release};n.Jd=function(){this.ia="s2"};n.Ld=function(a){this.ia="s2";a=a.data.baseClip;a.isAd?(this.Aa="ad",this.sa=a.isMid?"a2":"a1"):(this.Aa=M,this.sa="")};n.Wb=function(){if(this.ia!=O)this.ia="s3"};
n.Id=function(){this.ia="s4"};n.Kd=function(a){this.fd=a.currentTime};n.O=function(){return this.ga!=i};n.M=function(){return this.ga.title};n.N=function(){return!this.Ya?"":this.Ya};n.U=l("Aa");n.P=l("sa");n.ca=function(){return this.ga.duration};n.J=l("ia");n.X=l("fd");n.T=function(){return this.ga.bitrate};n.ba=function(){return this.ga&&this.ga.defaultThumbnailUrl?this.ga.defaultThumbnailUrl:this.ga.pid?"http://link.theplatform.com/s/ngc/"+this.ga.pid+"?format=poster&height=70&width=95":""};
n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:this.B===d?0:u()-this.B};n.$=function(){var a=this.ga.keywords?this.ga.keywords.split(","):[],b=[];t(this.ga.categories?this.ga.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};n.Q=k();n.aa=m("TP");Y.prototype.initialize=Y.prototype.xd;Y.prototype.getStrategyName=Y.prototype.aa;Y.prototype.isReady=Y.prototype.O;Y.prototype.getTitle=Y.prototype.M;
Y.prototype.getVideoPath=Y.prototype.N;Y.prototype.getContentType=Y.prototype.U;Y.prototype.getAdPosition=Y.prototype.P;Y.prototype.getTotalDuration=Y.prototype.ca;Y.prototype.getState=Y.prototype.J;Y.prototype.getCurrentPlayTime=Y.prototype.X;Y.prototype.getBitrate=Y.prototype.T;Y.prototype.getThumbnailPath=Y.prototype.ba;Y.prototype.getPlayerType=Y.prototype.Z;Y.prototype.getAutoplayType=Y.prototype.S;Y.prototype.getViewStartTime=Y.prototype.da;Y.prototype.getSections=Y.prototype.$;
Y.prototype.getAuthors=Y.prototype.Q;Y.verify=function(a){return typeof a.controller!=="undefined"};function Lc(a,b){this.a=a;this.Pc=b;this.Na=window.location!=window.parent.location;this.Ic=j;this.de=u();this.Oc="_v_";this.ta={};L.call(this)}ea(Lc,L);var Mc=q.QUICK_TEST?1E4:6E4,Nc="autoDetect",Oc={je:"title",ke:"videopath",ie:"thumbnailpath"},Pc={};n=Lc.prototype;
n.H=function(){this.Sb=(this.Ta=this.q.F("_chartbeat3"))?0:1;this.lc=this.cc=g;this.Ib=j;this.ub=this.$b=this.sc=this.Ga=d;this.La=15E3;this.hb=d;this.ib=this.jb=0;this.Jb=j;this.Xd=this.ic=this.zb=0;var a=q.location;this.ac=j;if(!this.Ta||this.Ta.length===0)this.Ta=qa(Ub(this),3);this.q.create("_chartbeat3",this.Ta,34128E3);var b;(b=this.Pc)&&Ja(b)?(this.ea=new b(this.a),b=g):b=j;if(b){C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",a.hostname);C(this.k,
"path",Mb(!!this.k.useCanonical));this.ea.getPlayerType&&C(this.k,"video_type",this.ea.getPlayerType());this.sc=setInterval(v(this.cd,this),1E3);if(this.Na===g)this.qb=v(this.td,this),x(window,"message",this.qb),this.hb=setInterval(this.Yd,1E3);Lc.ka.H.call(this)}};n.Fb=k();
n.na=function(){if(this.ea){if(!Qc(this))this.lc=g;if(!this.lc)return u()-this.Fa>=this.pb&&clearInterval(this.Ga),Lc.ka.na.call(this);if(this.ea.isReady())this.Ib=this.lc=j,this.$b=Rc(this),Sc(this),this.Ga=setInterval(v(this.Hb,this),100),Lc.ka.na.call(this);else if(!this.Ib){this.Ib=g;if(this.Xd++>150)throw"Error: Video strategy never reported its ready state";Tc(this,100)}}};
n.Ua=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),e=Qc(this),f=this.Na?[]:q._cbq||(q._cbq=[]),h=b.getViewStartTime(),p=Uc(this),r=b.getAutoplayType?b.getAutoplayType():d,h=h===-1?-1:h/1E3,p=p?encodeURIComponent(p):d;if(!Pc.path||Pc.path===e||c==="s2"&&Pc.state!=="s2")switch(Pc={path:e,state:c},f.push(["_vi",La(Vc(this))]),f.push(["_vp",e]),f.push(["_vdd",La(Wc(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",La(Uc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Xc(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Jb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",h)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",p)+Z("_vaup",r||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.ic)+Z("c",Math.round(Pa(this.de)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.zb+"&j="+(this.La/1E3+15)+Yc(this)+"&tz="+(new Date).getTimezoneOffset()+(Lb(this.q)?"&l=1":"")+"&_";this.Na===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.eb(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}n.bb=function(){this.q.update("_cb_cp",this.Ca,60,j,",")};function Yc(a){var b=a.q.F("_cb_cp");a.q.remove("_cb_cp");return b?"&D="+b:""}
function Zc(a){return a.k.subdomain?a.k.subdomain:ta(q.location.hostname)}function Wc(a){var b=a.k,a=a.ea,b=b.videodomain||a.getHost&&a.getHost()||b.domain;return"video@"+(b&&b.replace(/^video@/,""))}function Qc(a){var b=a.ta.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Vc(a))return qa(a)}else return a.ea.getVideoPath();return""}function Vc(a){return a.ta.title||a.ea.getTitle()}function Uc(a){return a.ta.thumbnailpath||a.ea.getThumbnailPath()}
function Xc(a){var b=a.k,c=a.ea,e=c.getUid&&c.getUid()||b.uid,f=La(Wc(a)),h="",p=a.cb?"&b="+a.cb:"",r,o=a.k.path;r=a.k.useSubDomains!==j&&o&&o.substr(0,1)==="/"?Zc(a)+o:o;var o=c.getSections&&c.getSections(),E=c.getAuthors&&c.getAuthors(),H=b.sections?"&g0="+encodeURIComponent(b.sections):"",R=b.authors?"&g1="+encodeURIComponent(b.authors):"",o=o===d||b.videoPageGroups?H:"&g0="+encodeURIComponent(o.join(",")),E=E===d||b.videoPageGroups?R:"&g1="+encodeURIComponent(E.join(",")),R="",H=Qc(a);if(a.ub===
d)a.ub=H;else if(H!=a.ub)R=Z("D",a.Ca),a.Ca=qa(Ub(a)),a.ub=H,a.jb=0,a.ib=0,a.zb=0,a.ic=0,a.Jb=$c(a)&&!ad(a),a.cc=g;if(a.cc||R){if(a.Na===j||a.Na===g&&a.Ic===g)a.cc=j;h=(Vb(a)?"&v=":"&r=")+Wb(a)}a.zb+=a.jb;a.jb=0;a.ic+=a.ib;a.ib=0;Sc(a);var X=H="",ga="",ca="",N="",D="",ka="",la="";if(!a.Na===g||a.ac===g)H="&_vi="+cc(a),X="&_vp="+encodeURIComponent(r),ga="&_vh="+La(Zc(a)),ca="&_vdd="+encodeURIComponent(b.domain),a.ac===g?(N=b.u,D=b.t,ka=Za(b.v),la=Za(b.r)):(N=I("u"),D=I("t"),ka=Za(I("v")),la=Za(I("r")));
r="";r=Ia(ka)?"&_pv="+ka:Ia(la)?"&_pr="+la:"&_pr=NA";ka="&_pu=";la="&_pt=";ka+=N?N:"NA";la+=D?D:"NA";N=!b.noCookies&&a.q.isSupported();D=c.getStrategyName?c.getStrategyName():"";return Ma()+"//"+b.pingServer+"/ping?h="+f+"&g="+e+"&p="+La(Qc(a))+"&i="+La(Vc(a))+o+E+"&u="+a.Ta+"&t="+a.Ca+"&x=0&y=0&V=94"+Z("VS",D)+(N?"&n="+a.Sb:"&nc=1")+p+h+R+Z("_vd",c.getTotalDuration())+H+X+ga+ka+la+r+ca}n.Hb=function(){if($c(this)&&!ad(this))this.Jb=g;var a=Rc(this);if(this.$b!=a)this.$b=a,Sc(this),this.na()};
function Sc(a){var b=a.La;a.La=$c(a)?a.zb<60?5E3:15E3:Mc;b!=a.La&&Tc(a,a.La)}function Tc(a,b){clearInterval(a.lb);a.La=b;a.lb=setInterval(v(a.na,a),b)}function Rc(a){return a.ea.getState()+a.ea.getContentType()}function $c(a){return a.ea.getState()==="s2"||ad(a)}function ad(a){return a.ea.getContentType()==="ad"}n.cd=function(){$c(this)===g&&(this.jb+=1,this.ea.getContentType()===M&&(this.ib+=1))};n.Yd=function(){window.parent.postMessage("cbdata?","*")};
n.td=function(a){if(a.source===window.parent&&(a=a.data,Ia(a)&&a.indexOf("domain=")===0)){this.ac=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ga(window,"message",this.qb);clearInterval(this.hb);this.hb=d;this.Ic=g;this.na()}};n.setProperty=function(a,b){var c=j,e=this;t(Oc,function(f){if(a.toLowerCase()==f)return e.ta[f]=b,c=g,j});return c};
n.terminate=function(){clearInterval(this.sc);clearInterval(this.hb);clearInterval(this.Ga);Ga(window,"message",this.qb);Lc.ka.terminate.call(this)};n.wa=function(){Lc.ka.wa.call(this);this.Pc=this.a=this.qb=i};function $(a){this.a=a;this.G=g;this.D=j;this.B=u();this.Ga=this.ya=this.Ba=d;this.ha()}n=$.prototype;n.ha=function(){this.Ga=setInterval(s(this.Hb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.fa()};n.Hb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ga),this.Ga=d,this.fa()};n.fa=function(){if(!this.D)this.D=g};function bd(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}n.O=l("G");
n.M=function(){var a="";Ja(this.a.getVideoData)&&(a=(a=this.a.getVideoData())&&a.title||"");return a};n.N=function(){return bd(this)||this.a.getVideoUrl()};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.getDuration();return Ha(a)?a*1E3:a};n.J=function(){if(!this.D)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};n.X=function(){var a=this.a.getCurrentTime();return y(a)};n.T=m(-1);n.ba=function(){return"http://img.youtube.com/vi/"+bd(this)+"/default.jpg"};
n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Pa(this.B)};n.$=l("Ba");n.Q=l("ya");n.aa=m("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.M;$.prototype.getVideoPath=$.prototype.N;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.J;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return Ja(a.getDuration)&&Ja(a.getVideoUrl)&&Ja(a.getVideoEmbedCode)};function cd(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(W);q._cbv_strategies.push(T);q._cbv_strategies.push(S);q._cbv_strategies.push($);q._cbv_strategies.push(U);q._cbv_strategies.push(Q);q._cbv_strategies.push(P);q._cbv_strategies.push(V);q._cbv_strategies.push(Y);this.jc=[];this.ta=[];this.k=q._sf_async_config||{};Fb("_cbv",v(this.ud,this));if(this.k[Nc]!==j)this.kd=Xa(v(this.wc,this),5E3),this.wc(),setTimeout(v(this.Ha,this),3E4)}
cd.prototype.ud=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){dd();return}else if(b==="removePlayer"){ed(this,a[1]);return}else if(b==="setProps"){fd(a[1])||this.ta.push(a[1]);return}}gd(this,a)};function gd(a,b){var c=j,e=q._cbv_strategies;w(window.jwplayer)&&(b=Ja(b)?b():b);t(e,function(a){if(a.verify(b)===g)return c=a,j});c===j||hd(a,b,c)}
function ed(a,b){var c=a.jc,e=q.pSUPERFLY_video,f=Na(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Na(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].wa()}function fd(a){if(!w(a))return j;var b=a.player,c=Oa(function(a){return a.a===b});return!w(c)?j:id(c,a)}function id(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function hd(a,b,c){var e=j;t(a.jc,function(a){if(b===a)return e=g,j});if(!e){c=new Lc(b,c);q.pSUPERFLY_video.push(c);for(var f=a.ta.length-1;f>-1;f--)id(c,a.ta[f])&&a.ta.splice(f,1);Zb(c);a.jc.push(b)}}
cd.prototype.wc=function(){if(Ja(window.jwplayer)&&w(window.jwplayer())){this.Ha();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else window.flowplayer?(this.Ha(),window._cbv.push(window.flowplayer)):window.brightcove&&window.experienceJSON?(this.Ha(),window._cbv.push(window.brightcove)):window.videojs?(this.Ha(),a=window.videojs.plugin,Ja(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?(this.Ha(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):
window.$pdk?(this.Ha(),window._cbv.push(window.$pdk)):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})};cd.prototype.Ha=function(){Ua(this.kd)};
function dd(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var h=f.src,p=h&&h.indexOf("www.youtube.com/embed/");h&&p>=0&&p<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var jd=new Cc,kd={};q.pSUPERFLY=kd;var ld=!!uc;kd.virtualPage=function(a,b){if(!pb){var c=q._sf_async_config;c.virtualReferrer=Ma()+"//"+c.domain+c.path;c.path=Ob(a);b&&(c.title=b);jd.kb();ld&&uc.evps();jd.Nc();ld&&uc.svps()}};kd.activity=v(jd.Wc,jd);Zb(jd);var md=G.Y(g);if(md)if(md.getItem("_cb_ip")){var nd=q.location;(!/^(.+[.])?chartbeat\.com$/.test(nd.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(nd.pathname))||Ac()}else x(q,"message",
Bc)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new cd;})();
